config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :courses
  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations" }

  root 'courses#index'

  resources :lectures do
    resources :comments
  end

  resources :lectures do
    member do
      put "like" => "lectures#upvote"
      put "unlike" => "lectures#downvote"
    end
  end

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  has_many :comments,:dependent=>:delete_all
  mount_uploader :attach, FileUploader
  acts_as_votable
  validates :title , :presence=>true
  validates :content , :presence=>true
  validates :attach , :presence=>true
end

app/controllers/lectures_controller.rb
class LecturesController < InheritedResources::Base
  before_action :authenticate_user!,only: [:downvote, :upvote]
  def index
    redirect_to courses_path
  end
  def create
    @lecture = Lecture.new(lecture_params)
    @lecture.user_id = current_user.id

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end

  end

  def upvote
    @lecture = Lecture.find(params[:id])
    @lecture.upvote_from current_user
    redirect_to lecture_path
  end

  def downvote
    @lecture = Lecture.find(params[:id])
    @lecture.downvote_from current_user
    redirect_to lecture_path
  end

  private

    def lecture_params
      params.require(:lecture).permit(:title, :attach, :content, :user_id, :course_id)
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<head>
  <style>
    .bg-1 {
      background-color: #1abc9c;
      /*color: #e65c00;*/
    }
  </style>

</head>

<div class="bg-1">
  <div class="container text-center">
    <%= form_for(@lecture) do |f| %>
        <% if @lecture.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

              <ul>
                <% @lecture.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </div>
        <div class="field" align="center">
          <%= f.label :attach %><br>
          <%= f.file_field :attach %>
        </div>
        <div class="field">
          <%= f.label :content %><br>
          <%= f.cktext_area :content %>
        </div>

        <div class="field" >
          <%= f.label :course_id %><br>
          <%= f.collection_select :course_id, current_user.courses,:id,:title, include_blank: true %>

        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>


  </div>
</div>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>
<%= link_to 'Back', lectures_path %>

<%= render 'form' %>

<%= link_to 'Show', @lecture %> |

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lectures</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Attach</th>
      <th>Content</th>
      <th>User</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.title %></td>
        <td><a href="<%= lecture.attach_url %>" download>Download Attachment</a></td>
        <td><%= raw lecture.content %></td>
        <td><%= lecture.user.name %></td>
        <td><%= lecture.course.title %></td>
        <td><%= link_to 'Show', lecture %></td>

        <% if current_user.id == lecture.user_id %>
            <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
            <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>
<%= link_to 'Back', lectures_path %>

<%= render 'form' %>

app/views/lectures/show.html.erb
<head>
  <style>
    .bg-1 {
      background-color: #1abc9c;
      color: #ffffff;
    }
    .borderless {
      border:none;
    }
  </style>
  </head>



<p id="notice"><%= notice %></p>
<a href="/courses/<%= @lecture.course.id %>" >Back</a>
<div class="container">
<div class="bg-1">


    <h1 align="center">Course Name:  <%= @lecture.course.title %></h1>

    <div class="text-align:center;" align="center">
      <%= link_to like_lecture_path(@lecture), class:"like" , method: :put do %>
          <button type="button" clas="btn btn-info" aria-label="Left Align">

            <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center " aria-hidden="true"> </span>
            <span class="bage"><%= @lecture.get_upvotes.size %></span>
          </button>

      <% end  %>


      <%= link_to unlike_lecture_path(@lecture), class:"like" , method: :put do %>
          <button type="button" clas="btn btn-info" aria-label="Left Align">

            <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center " aria-hidden="true"> </span>
            <span class="bage"><%= @lecture.get_downvotes.size %></span>
          </button>

      <% end  %>

    </div>

    <table class="table" border="none">

      <tbody>
      <tr>
        <td><h3>By: <%= @lecture.user.name %></h3><br><h3><%= @lecture.title %></h3></td>
        <td> </td>
      </tr>
      <tr>
        <td><h3><%= raw @lecture.content %></h3></td>
        <td><h5><a href="<%= @lecture.attach_url %>" download>Download Attachment</a></h5></td>
      </tr>
      </tbody>
      </table>
<div align="center">
  <% if (current_user.id ==  @lecture.user_id)&&(current_user.role == "instractor") %>

<%= link_to 'Edit', edit_lecture_path(@lecture) ,class:"btn btn-default" ,style:"text-decoration: none"%>
      <% end %>
</div>

  </div>



    <h4> the comments </h4>

    <div id="comments">
      <%= render :partial => @lecture.comments %>
    </div>

    <%= simple_form_for [@lecture ,Comment.new] do |f| %>

        <p>
          <%= f.input :content , :lable => "NEW COMMENT" , as: :text , input_html: { row:"3" } %>
        </p>

        <div class="btn">
          <%= f.submit "Add Comment " , class:'btn btn-primary'  %>
        </div>

    <% end %>

</div>