config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :courses
  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations" }

  root 'courses#index'

  resources :lectures do
    resources :comments
  end

  resources :lectures do
    member do
      put "like" => "lectures#upvote"
      put "unlike" => "lectures#downvote"
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :lecture
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base

  before_action :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :find_lecture
  def create
    @lecture = Lecture.find(params[:lecture_id])
    @comment = @lecture.comments.create(comment_params)
    @comment.user_id = current_user.id #or whatever is you session name
    if @comment.save
      redirect_to @lecture
    else
      flash.now[:danger] = "error"
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to lecture_path(@comment.lecture_id), notice: 'Comment was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to lecture_path(@comment.lecture_id), notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    def find_lecture
      @lecture=Lecture.find(params[:lecture_id])
    end
    def comment_params
      params.require(:comment).permit(:content, :user_id, :lecture_id)
    end
  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="container">
  <ul class="list-group">
    <%= div_for(comment) do  %>
  <li class="list-group-item"><span class="badge"><%= time_ago_in_words(comment.created_at) %></span> <%= h(comment.content) %></li>
        <% if current_user.id ==  comment.user_id %>
            <%= link_to 'Edit', edit_lecture_comment_path(comment.lecture,comment),class:"btn btn-primary" %> |
            <%= link_to 'Delete', lecture_comment_path(comment.lecture,comment), method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-primary" %>
        <% end %>
    <% end %>
  </ul>
</div>

app/views/comments/_form.html.erb
<%= form_for [@lecture,@lecture.comments.build] do |f| %>


  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', lecture_path(@comment.lecture) %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Lecture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user %></td>
        <td><%= comment.lecture %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Lecture:</strong>
  <%= @comment.lecture %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>