config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :courses
  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations" }

  root 'courses#index'

  resources :lectures do
    resources :comments
  end

  resources :lectures do
    member do
      put "like" => "lectures#upvote"
      put "unlike" => "lectures#downvote"
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base
  before_action :authenticate_user!
  def create
    @course = Course.new(course_params)
    @course.user_id = current_user.id

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end


  end
  private

    def course_params
      params.require(:course).permit(:title, :image, :desc, :user_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<head>
  <style>
    .bg-1 {
      background-color: #1abc9c;
      /*color: #ffffff;*/
    }
  </style>

</head>

<div class="bg-1">
  <div class="container text-center">

    <%= form_for(@course) do |f| %>
        <% if @course.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

              <ul>
                <% @course.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </div>
        <div class="field" align="center">
          <%= f.label :image %><br>
          <%= f.file_field :image %>
        </div>
        <div class="field">
          <%= f.label :desc %><br>
          <%= f.cktext_area :desc %>
        </div>

        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>

  </div>
</div>

app/views/courses/edit.html.erb
<h1 align="center" >Editing Course</h1>
<%= link_to 'Back', courses_path %>

<%= render 'form' %>


<%= link_to 'Show', @course %> |

app/views/courses/index.html.erb
<div class="alert alert-danger">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <p id="notice" ><%= notice %></p>
</div>

<head>
  <style>
    .hovereffect {
      width:100%;
      height:100%;
      float:left;
      overflow:hidden;
      position:relative;
      text-align:center;
      cursor:default;
    }

    .hovereffect .overlay {
      width:100%;
      height:100%;
      position:absolute;
      overflow:hidden;
      top:0;
      left:0;
      opacity:0;
      background-color:rgba(0,0,0,0.5);
      -webkit-transition:all .4s ease-in-out;
      transition:all .4s ease-in-out
    }

    .hovereffect img {
      display:block;
      position:relative;
      -webkit-transition:all .4s linear;
      transition:all .4s linear;
    }

    .hovereffect h2 {
      text-transform:uppercase;
      color:#fff;
      text-align:center;
      position:relative;
      font-size:17px;
      background:rgba(0,0,0,0.6);
      -webkit-transform:translatey(-100px);
      -ms-transform:translatey(-100px);
      transform:translatey(-100px);
      -webkit-transition:all .2s ease-in-out;
      transition:all .2s ease-in-out;
      padding:10px;
    }

    .hovereffect a.info {
      text-decoration:none;
      display:inline-block;
      text-transform:uppercase;
      color:#fff;
      border:1px solid #fff;
      background-color:transparent;
      opacity:0;
      filter:alpha(opacity=0);
      -webkit-transition:all .2s ease-in-out;
      transition:all .2s ease-in-out;
      margin:50px 0 0;
      padding:7px 14px;
    }

    .hovereffect a.info:hover {
      box-shadow:0 0 5px #fff;
    }

    .hovereffect:hover img {
      -ms-transform:scale(1.2);
      -webkit-transform:scale(1.2);
      transform:scale(1.2);
    }

    .hovereffect:hover .overlay {
      opacity:1;
      filter:alpha(opacity=100);
    }

    .hovereffect:hover h2,.hovereffect:hover a.info {
      opacity:1;
      filter:alpha(opacity=100);
      -ms-transform:translatey(0);
      -webkit-transform:translatey(0);
      transform:translatey(0);
    }

    .hovereffect:hover a.info {
      -webkit-transition-delay:.2s;
      transition-delay:.2s;
    }
    .jumbotron {
      background-color: #1abc9c;
      color: #ffffff;
    }

  </style>
</head>
<div class="container">
  <div class="jumbotron">
    <h1>Open Coresra</h1>
    <p>New window for technology.. Think out of the box.</p>
  </div>
  <div align="center">
    <% if current_user.role == "instractor" %>

  <%= link_to 'Add New Course', new_course_path , class:"btn btn-info" ,style:"text-decoration: none" %>
    <% end %>
  </div>
<table>
  <tbody>

    <% @courses.each do |course| %>
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <h2 align="center"> <%= course.title %></h2>
        <h3 align="center">Added by: <%= course.user.name %></h3>
        <div class="hovereffect">

          <image class="img-responsive img-thumbnail" src="<%= course.image %>" style="width:250px ;height:200px "></image>
          <div class="overlay">
            <h2>Coursera</h2>
            <a class="info" href="/courses/<%= course.id %>">Show</a>
            <% if current_user.id == course.user_id %>
                <a class="info" href="<%= edit_course_path(course) %>">Edit</a>
                <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } ,class:"info" %>
          <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </tbody>
</table>

</div>

app/views/courses/new.html.erb
<h1 align="center" >New Course</h1>
<%= link_to 'Back', courses_path %>

<%= render 'form' %>

app/views/courses/show.html.erb
<head>
  <style>
    .bg-1 {
      background-color: #1abc9c;
      color: #ffffff;
    }
  </style>
</head>
<%= link_to 'Back', courses_path %>

<p id="notice"><%= notice %></p>

<div class="bg-1">
  <div class="container text-center">
    <h1><%= @course.title %></h1>
    <image src="<%= @course.image %>"class="img-responsive img-thumbnail" width="650" height="350"></image>
    <h3>By:  <%= @course.user.name %></h3>
    <p> <%= raw @course.desc %></p>
    <% if (current_user.id ==  @course.user_id)&&(current_user.role == "instractor") %>
        <%= link_to 'Edit', edit_course_path(@course) ,class:"btn btn-default" ,style:"text-decoration: none"%>
        <%= link_to 'New Lecture', new_lecture_path ,class:"btn btn-default" ,style:"text-decoration: none"%>

  <% end %>
  </div>
</div>



<div class="list-group">
  <a class="list-group-item disabled">Lectures:</a>
  <% @course.lectures.each do |lecture|%>
      <%= link_to  lecture.title ,lecture ,class: "list-group-item"%>

  <% end %>
</div>



|